[tool.poetry]
name = "ssh_util"
version = "0.1.0"
description = "ssh command utility"
authors = ["Takayuki Shimizukawa <shimizukawa@gmail.com>"]
license = "Apache-2.0"
readme = "README.rst"
include = ["CHANGELOG.rst"]

[tool.poetry.dependencies]
python = "^3.6"
cryptography = "^2.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
ssh_util = "ssh_util.main:main"
